source = ~/.cache/wal/colors-hyprland.conf

# BACKGROUND
background {
    monitor =
    path = ~/.config/hypr/hyprlock.jpg
    blur_passes = 2
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

# GENERAL
general {
    no_fade_in = false
    grace = 0
    disable_loading_bar = false
}

# INPUT FIELD
input-field {
    monitor =
    size = 250, 60
    outline_thickness = 2
    dots_size = 0.2 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.2 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    outer_color = $color3
    inner_color = $color0
    font_color = $color7
    fade_on_empty = false
    font_family = SF Pro Display Bold
    placeholder_text = <i>Hi, $USER</i>
    hide_input = false
    position = 0, -290
    halign = center
    valign = center
    rounding = 0
}

# Hour-Time
label {
    monitor =
    text = cmd[update:1000] echo -e "$(date +"%H")"
    color = $color3
    font_size = 160
    font_family = AlfaSlabOne 
    position = 0, 300
    halign = center
    valign = center
}

# Minute-Time
label {
    monitor =
    text = cmd[update:1000] echo -e "$(date +"%M")"
    color = $color7
    font_size = 160
    font_family = AlfaSlabOne
    position = 0, 100
    halign = center
    valign = center
}

# Day-Date-Month
label {
    monitor =
    text = cmd[update:1000] echo "<span>$(date '+%A, ')</span><span>$(date '+%d %B')</span>"
    font_size = 30
    color = $color7
    font_family = SF Pro Display Bold
    position = 0, -15
    halign = center
    valign = center
}

# USER
image {
    monitor =
    path = ~/.config/hypr/profile.jpg
    rounding = 250
    size = 150
    position = 0, -150
    halign = center
    valign = center
}

